config/routes.rb
Rails.application.routes.draw do
  root :to => 'homes#top'
  resource :users, only: [:new, :show, :edit, :create, :update]
  get 'login', to: 'sessions#new', as: 'new_sessions'
  post 'login', to: 'sessions#create', as: 'create_sessions'
  delete 'logout', to: 'sessions#destroy', as: 'destroy_sessions'
  resources :memos, only: [:index, :update, :destroy, :create]
  post 'ajax_memos_create', to: 'memos#ajax_create', as: 'ajax_memos_create'
  get 'search', to: 'memos#search', as: 'search'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/memo.rb
class Memo < ApplicationRecord
    belongs_to :user, class_name: "User", foreign_key: "user_id"

    validates :user_id, presence: true
    validates :title, presence: true, length: { minimum: 2, maximum: 32 }
    validates :description, presence: true, length: { minimum: 2, maximum: 140 }
end

app/models/user.rb
class User < ApplicationRecord
    has_many :memos, class_name: "Memo", foreign_key: "user_id"

    validates :name, presence: true, length: {minimum:2, maximum:32}
    validates :email, presence: true, uniqueness: true
    validates :password, presence: true, format: {with: /^[0-9a-zA-Z]+$/, multiline: true}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    def current_user
        if session[:user_id]
          @current_user = User.find(session[:user_id])
        else
          flash[:alert] = "ログインする必要があります。"
          redirect_to new_sessions_path
        end
    end

    def logged_in?
        if session[:user_id]
            @current_user = User.find(session[:user_id])
            flash[:notice] = "すでにログインしています。"
            redirect_to memos_path
        end
    end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
    before_action :logged_in?, only: [:top]

    def top
    end

end

app/controllers/memos_controller.rb
class MemosController < ApplicationController
  before_action :current_user

  def index
    @memo_new = Memo.new
    @memos = @current_user.memos
  end

  def create
    @memo_new = Memo.new(memos_params)
    @memos = Memo.all
    if @memo_new.save
      redirect_to memos_path
    else
      render action: "index"
    end
  end

  def update
    @memo = Memo.find(params[:id])
    @memo.update(memos_params)
    redirect_to memos_path
  end

  def destroy
    @memo = Memo.find(params[:id])
    @memo.destroy
    redirect_to memos_path
  end

  def ajax_create
    @memo_new = Memo.new(memos_params)
    @memo_new.user_id = @current_user.id
    @memos = @current_user.memos

    if @memo_new.save
      flash.now[:notice] = "メモの保存に成功しました。"
    else
      flash.now[:alert] = "メモの保存に失敗しました。"
    end
  end

  def search
    seach_word = params[:word]
    @memos = @current_user.memos.where("title LIKE ? or description LIKE ?", "%#{seach_word}%", "%#{seach_word}%")
    if @memos.count > 0
      flash.now[:notice] = "#{@memos.count}件のメモが見つかりました。"
    else
      flash.now[:alert] = "#メモが見つかりませんでした。"
    end
  end

  private

  def memos_params
    params.require(:memo).permit(:title, :description, :user_id)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    before_action :logged_in?, only: [:new, :create]

    def new

    end

    def create
        @current_user = User.find_by(email: params[:email], password: params[:password])
        if @current_user
            session[:user_id] = @current_user.id
            flash[:notice] = "ログインに成功しました。"
            redirect_to memos_path
        else
            flash[:alert] = "ログインに失敗しました。"
            render action: "new"
        end
    end

    def destroy
        session[:user_id] = nil
        redirect_to new_sessions_path
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :current_user, only: [:show, :edit, :update]
    before_action :logged_in?, only: [:new, :create]

    def new
        @user_new = User.new
    end

    def show
        @user = User.find(session[:user_id])
    end

    def edit
        @user = User.find(session[:user_id])
    end

    def create
        @user_new = User.new(user_params)
        if @user_new.save
            session[:user_id] = @user_new.id
            flash.now[:notice] = "ユーザーの新規登録に成功しました。"
            redirect_to memos_path
        else
            flash.now[:alert] = "ユーザーの新規登録に失敗しました。"
            render action: "new"
        end
    end

    def update
        @user = User.find(session[:user_id])
        if @user.update(user_params)
            redirect_to users_path
            flash.now[:notice] = "ユーザー情報の更新に成功しました。"
        else
            render action: "edit"
            flash.now[:alert] = "ユーザー情報の更新に失敗しました。"
        end
    end

    private
    def user_params
        params.require(:user).permit(:name, :email, :password)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/memos_helper.rb
module MemosHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/top.html.erb
<div class="wrapper">
    <div class="container mv-image">
        <div class="mv-imag-transparent">
            <div class="top-container">
               <div class="col-box-1">
                    <h2>ようこそMemoAppへ!</h2>
                </div>
                <div class="col-box-1">
                    <p>MemoAppは、無料で利用できるメモアプリです。</p>
                    <br>
                    <p>いつでも、どこでも、思いついたらすぐに記録することができるシンプルな機能を提供しています。</p>
                    <br>
                    <p>ぜひ、ご活用ください。</p>
                </div>
                <div class="col-box-1">
                    <%= link_to "新規登録", new_users_path, method: :get, class: "btn-100 green-color" %>
                    <%= link_to "ログイン", new_sessions_path, method: :get, class: "btn-100 blue-color" %>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
    <h3><%= obj.errors.count %>件のエラーが発生しました。</h3>
    <ul>
        <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
    </ul>
<% end %>

app/views/layouts/_notice.html.erb
<% if flash[:notice] %>
    <div class="wrapper green-color">
        <div class="container notice-text">
            <%= flash[:notice] %>
        </div>
    </div>
<% end %>

<% if flash[:alert] %>
    <div class="wrapper red-color">
        <div class="container notice-text">
            <%= flash[:alert] %>
        </div>
    </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MemoApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@rails/ujs@6.0.2/lib/assets/compiled/rails-ujs.js"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <div class="wrapper header-color">
      <div class="container flex-between">
        <div class="header-left">
          <h1><%= link_to "MemoApp", root_path, method: :get %></h1>
        </div>

        <div class="header-right">
          <% if @current_user.nil? %>
            <%= link_to "新規登録", new_users_path, method: :get %>
            <%= link_to "ログイン", new_sessions_path, method: :get %>
          <% else %>
            ログインユーザー：<%= @current_user.name %>さん
            <%= link_to "登録情報", users_path, method: :get %>
            <%= link_to "ログアウト", destroy_sessions_path, method: :delete %>
          <% end %>
        </div>
      </div>
    </div>

    <div id="notice">
      <%= render "layouts/notice" %>
    </div>

    <%= yield %>
  </body>
</html>

app/views/memos/_form.html.erb
<%= form_with model: memo_new, url: ajax_memos_create_path, local: false, method: :post do |f| %>
    <div class="memo-header">
        <%= f.text_field :title, placeholder: "タイトル", class: "form-box" %>
    </div>
    <div class="memo-center">
        <%= f.text_area :description, placeholder: "メモ", class: "form-box" %>
    </div>
    <div class="memo-footer">
        <%= f.submit "作成", class: "btn" %>
    </div>
<% end %>

app/views/memos/_list.html.erb
<% memos.reverse.each do |memo| %>
    <div class="col-box-3">
        <%= render "memos/show", memo: memo %>
    </div>
<% end %>

app/views/memos/_show.html.erb
<%= form_with model: memo, url: memo_path(memo.id), local: true, method: :patch do |f| %>
    <div class="memo-header">
        <%= f.text_field :title, placeholder: "タイトル", class: "form-box" %>
    </div>
    <div class="memo-center">
        <%= f.text_area :description, placeholder: "メモ", class: "form-box" %>
    </div>
    <div class="memo-footer">
        <%= f.submit "更新", class: "btn" %>
    </div>
<% end %>
<div class="memo-other">
    <%= button_to "削除", memo_path(memo.id), method: :delete, class: "btn" %>
</div>

app/views/memos/ajax_create.js.erb
$('#memo-list').html("<%= j(render "memos/list", memos: @memos) %>");
$('#errors').html("<%= j(render "layouts/errors", obj: @memo_new) %>");
$('#memo-post').find('.form-box').val('');
$('#notice').html("<%= j(render "layouts/notice") %>").show().fadeOut(2000);

app/views/memos/index.html.erb
<div class="wrapper">
    <div class="container flex-start">
        <div class="col-box-1">
            <%= form_with url: search_path, local: false, method: :get do |f| %>
                <%= f.text_field :word, placeholder: "検索したいメモの内容を記入してください。", class: "search-box" %>
                <%= f.submit "検索", class: "btn" %>
            <% end %>
        </div>

        <div class="col-box-1">
            <h2>メモ一覧</h2>
        </div>

        <div class="col-box-3" id="memo-post">
            <%= render "memos/form", memo_new: @memo_new %>
        </div>

        <div class="col-box-2" id="errors">
            <%= render "layouts/errors", obj: @memo_new %>
        </div>
     </div>

    <div class="container flex-start" id="memo-list">
        <%= render "memos/list", memos: @memos %>
    </div>
</div>

app/views/memos/search.js.erb
$('#memo-list').html("<%= j(render "memos/list", memos: @memos) %>");
$('#notice').html("<%= j(render "layouts/notice") %>").show().fadeOut(2000);

app/views/users/edit.html.erb
<div class="wrapper">
    <div class="container">
        <h2>ユーザー編集</h2>

        <%= form_with model: @user, url: users_path, local: true, method: :patch do |f| %>
            <%= f.label :name, "Name" %>
            <%= f.text_field :name, class: "form-box" %>

            <%= f.label :email, "Email" %>
            <%= f.email_field :email, class: "form-box" %>

            <%= f.submit "更新", class: "btn" %>
        <% end %>
    </div>
</div>

app/views/users/new.html.erb
<div class="wrapper">
    <div class="container">
        <h2>ユーザー新規登録</h2>

        <%= form_with model: @user_new, url: users_path, local: true, method: :post do |f| %>
            <%= f.label :name, "Name" %>
            <%= f.text_field :name, class: "form-box" %>

            <%= f.label :email, "Email" %>
            <%= f.email_field :email, class: "form-box" %>

            <%= f.label :password, "Password" %>
            <%= f.password_field :password, class: "form-box" %>

            <%= f.submit "新規登録", class: "btn" %>
        <% end %>
    </div>
</div>

app/views/users/show.html.erb
<div class="wrapper">
    <div class="container">
        <h2>ユーザー情報</h2>

        <div class="">
            <p>Name</p>
        </div>
        <div class="form-box">
            <%= @user.name %>
        </div>

        <div class="">
            <p>Email</p>
        </div>
        <div class="form-box">
            <%= @user.email %>
        </div>

        <%= link_to "編集", edit_users_path, method: :get %>

    </div>
</div>